apiVersion: apps/v1
kind: Deployment
metadata:
  name: httptester
  namespace: myci
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: httptester
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: httptester
          image: registry.cn-hangzhou.aliyuncs.com/hzzhangfan/test:0.0.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 20Mi
      imagePullSecrets:
      - name: dockerhub
---
kind: Service
apiVersion: v1
metadata:
  name: httptester
  namespace: myci
spec:
  selector:
    app: httptester
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---      
# 发布到Ingress,便于外部访问
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tektoncd-httptester-ingress
  namespace: myci
  annotations:
    kubernetes.io/ingress.class: "ambassador"
    ambassador.ingress.kubernetes.io/use-regex: "true"
    ambassador.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /httptester
        backend:
          serviceName: httptester
          servicePort: 80
---      
